GET http://localhost:5000/users

###
POST http://localhost:5000/users
Content-Type: application/json

{
    "username": "aap07",
    "name": "anton",
    "email": "anton@email.com",
    "password": "1234567",
    "confPassword": "1234567"
}
